window.HWS_ARCHIVE_CONFIG = {
  navItems: [
    { section: "dashboard", icon: "layout-dashboard", label: "经营驾驶舱", active: true },
    { section: "catalog", icon: "library-big", label: "内容检索总目录" },
    { section: "layout", icon: "blocks", label: "菜单模块编排" },
    { section: "tenant", icon: "building-2", label: "组织架构" },
    { section: "search", icon: "search", label: "全域智能检索" },
    { section: "keyword", icon: "list-filter", label: "组织项目检索" },
    { section: "workType", icon: "files", label: "电子文件类型" },
    { section: "inbox", icon: "hard-drive", label: "多源资料入库" },
    { section: "media", icon: "play-square", label: "媒体与转写中心" },
    { section: "finish", icon: "sparkles", label: "AI 补全评分" },
    { section: "permission", icon: "shield-check", label: "权限与审计" },
    { section: "integration", icon: "blocks", label: "平台接口中心" },
    { section: "agent", icon: "bot", label: "Agent 接入中心" },
    { section: "backup", icon: "database-backup", label: "备份与容灾" },
  ],

  secondaryMenus: [
    {
      section: "dashboard",
      title: "经营驾驶舱",
      hint: "全局指标、风险、任务和审计入口",
      items: [
        { label: "资产总览", moduleId: "metrics", query: "资产总览" },
        { label: "今日新增", moduleId: "metrics", query: "今日新增" },
        { label: "高密级告警", moduleId: "archiveResults", query: "L4 L5 L6" },
        { label: "存储端点", moduleId: "storageStatus", query: "硬盘 云端 NAS 邮箱 状态" },
        { label: "下载外发", moduleId: "downloadGovernance", query: "下载 邮箱 水印 审批" },
        { label: "今日台账", moduleId: "dailyLedger", query: "日报 台账 审计" },
        { label: "AI 待处理", moduleId: "finishPipeline", query: "待收尾 AI" },
        { label: "备份健康", moduleId: "finishPipeline", query: "备份快照" },
        { label: "部门排行", moduleId: "saas", query: "部门" },
      ],
    },
    {
      section: "layout",
      title: "菜单模块编排",
      hint: "一级菜单、二级材料、页面模块、尺寸和锁定统一配置",
      items: [
        { label: "一级菜单排序", moduleId: "layoutWorkbench", query: "一级菜单" },
        { label: "二级材料归属", moduleId: "layoutWorkbench", query: "二级材料" },
        { label: "页面模块尺寸", moduleId: "layoutWorkbench", query: "模块尺寸" },
        { label: "模块锁定", moduleId: "layoutWorkbench", query: "锁定" },
        { label: "菜单关联校验", moduleId: "layoutWorkbench", query: "菜单关联" },
      ],
    },
    {
      section: "catalog",
      title: "内容检索总目录",
      hint: "从一级到四级目录发现资料，再进入检索和预览",
      items: [
        { label: "一级目录", moduleId: "contentDirectory", query: "一级目录 公司 项目 资料" },
        { label: "二级目录", moduleId: "contentDirectory", query: "二级目录 部门 类型 年份" },
        { label: "三级目录", moduleId: "contentDirectory", query: "三级目录 文件格式 场景" },
        { label: "四级目录", moduleId: "contentDirectory", query: "四级目录 成品 半成品 版本" },
        { label: "内容关键词", moduleId: "command", query: "内容关键词" },
        { label: "目录命中结果", moduleId: "archiveResults", query: "目录" },
      ],
    },
    {
      section: "tenant",
      title: "组织架构",
      hint: "集团、项目公司、部门、人员和岗位关系",
      items: [
        { label: "集团公司", moduleId: "saas", query: "集团公司" },
        { label: "项目公司", moduleId: "saas", query: "项目公司" },
        { label: "部门建制", moduleId: "saas", query: "部门" },
        { label: "员工档案", moduleId: "archiveResults", query: "员工 作者" },
        { label: "岗位职能", moduleId: "archiveResults", query: "职能 岗位" },
        { label: "负责人等级", moduleId: "archiveResults", query: "负责人等级" },
        { label: "跨公司关联", moduleId: "archiveResults", query: "跨公司" },
      ],
    },
    {
      section: "search",
      title: "全域智能检索",
      hint: "搜索框、语音、条件组合和本机索引快搜",
      items: [
        { label: "全域搜索", moduleId: "command", query: "" },
        { label: "语音检索", moduleId: "command", query: "语音" },
        { label: "高级条件", moduleId: "command", query: "高级条件" },
        { label: "本机索引", moduleId: "command", query: "本机索引" },
        { label: "相似文件", moduleId: "archiveResults", query: "相似文件" },
        { label: "历史版本", moduleId: "archiveResults", query: "历史版本" },
        { label: "关联资料", moduleId: "archiveResults", query: "关联资料" },
        { label: "受控下载", moduleId: "downloadGovernance", query: "受控下载 水印 敏感数字" },
      ],
    },
    {
      section: "keyword",
      title: "组织项目检索",
      hint: "公司、项目、组织、个人、部门、职能和周期交叉检索",
      items: [
        { label: "公司", moduleId: "command", query: "公司" },
        { label: "项目", moduleId: "command", query: "项目" },
        { label: "组织", moduleId: "command", query: "组织" },
        { label: "个人", moduleId: "command", query: "员工 作者" },
        { label: "部门", moduleId: "command", query: "部门" },
        { label: "职能", moduleId: "command", query: "职能" },
        { label: "周期阶段", moduleId: "archiveResults", query: "周期阶段" },
      ],
    },
    {
      section: "workType",
      title: "电子文件类型",
      hint: "照片、声音、视频、邮件、办公文档、工程文件和压缩包",
      items: [
        { label: "照片图片", moduleId: "fileTypes", query: "照片 图片 JPG PNG HEIC" },
        { label: "音频录音", moduleId: "fileTypes", query: "音频 录音 MP3 WAV" },
        { label: "视频影视", moduleId: "fileTypes", query: "视频 MP4 MOV" },
        { label: "邮件附件", moduleId: "fileTypes", query: "邮件 EML MSG 附件" },
        { label: "PPT", moduleId: "fileTypes", query: "PPT PPTX KEY" },
        { label: "Word", moduleId: "fileTypes", query: "Word DOC DOCX" },
        { label: "Excel", moduleId: "fileTypes", query: "Excel XLSX CSV" },
        { label: "PDF", moduleId: "fileTypes", query: "PDF OFD" },
        { label: "扫描件", moduleId: "fileTypes", query: "扫描 OCR TIFF" },
        { label: "设计稿", moduleId: "fileTypes", query: "PSD AI CDR Figma" },
        { label: "代码", moduleId: "fileTypes", query: "代码 JS SQL JSON" },
        { label: "数据库", moduleId: "fileTypes", query: "数据库 SQL DB" },
        { label: "压缩备份", moduleId: "fileTypes", query: "ZIP RAR 7Z 备份" },
      ],
    },
    {
      section: "inbox",
      title: "多源资料入库",
      hint: "手机、平板、旧电脑、邮箱、云盘、NAS、企业微信和素材卡接入",
      items: [
        { label: "手机入库", moduleId: "intake", query: "手机" },
        { label: "iPad/平板", moduleId: "intake", query: "iPad 平板" },
        { label: "旧电脑", moduleId: "intake", query: "旧电脑 主机" },
        { label: "邮箱入库", moduleId: "intake", query: "邮箱 邮件" },
        { label: "企业微信离职数据", moduleId: "intake", query: "企业微信 离职 数据" },
        { label: "云盘入库", moduleId: "intake", query: "云盘" },
        { label: "NAS 总库", moduleId: "intake", query: "NAS" },
        { label: "端点状态", moduleId: "storageStatus", query: "端点 状态 同步 在线 离线" },
        { label: "导入动作审批", moduleId: "intake", query: "复制 删除 镜像 最高授权" },
        { label: "下载外发审批", moduleId: "downloadGovernance", query: "下载 外发 公司邮箱 水印" },
        { label: "杀毒隔离", moduleId: "validation", query: "杀毒 隔离 病毒" },
        { label: "扫描批次", moduleId: "batchHistory", query: "批次" },
        { label: "样本验证", moduleId: "validation", query: "样本验证" },
      ],
    },
    {
      section: "media",
      title: "媒体与转写中心",
      hint: "照片、声音、视频、抽帧、转写、摘要和素材版本",
      items: [
        { label: "媒体预览", moduleId: "archiveResults", query: "媒体预览" },
        { label: "录音转写", moduleId: "archiveResults", query: "录音 转写" },
        { label: "视频抽帧", moduleId: "archiveResults", query: "视频 抽帧" },
        { label: "照片识别", moduleId: "fileTypes", query: "照片 图片" },
        { label: "素材版本", moduleId: "archiveResults", query: "版本 素材" },
        { label: "摘要纪要", moduleId: "archiveResults", query: "摘要 纪要" },
      ],
    },
    {
      section: "finish",
      title: "AI 补全评分",
      hint: "完整度、密级建议、AI 候选、评分公式和待收尾作品池",
      items: [
        { label: "待收尾作品", moduleId: "finishPipeline", query: "待收尾" },
        { label: "完整度公式", moduleId: "formulas", query: "完整度" },
        { label: "密级建议", moduleId: "formulas", query: "密级" },
        { label: "AI 候选分", moduleId: "formulas", query: "AI 候选" },
        { label: "评分中心", moduleId: "finishPipeline", query: "评分" },
        { label: "人工复核", moduleId: "validation", query: "人工复核" },
      ],
    },
    {
      section: "permission",
      title: "权限与审计",
      hint: "不同角色看到不同模块，所有复制、打开、导出都留痕",
      items: [
        { label: "角色模板", moduleId: "saas", query: "角色模板" },
        { label: "密级矩阵", moduleId: "saas", query: "密级矩阵" },
        { label: "复制审批", moduleId: "archiveResults", query: "复制审批" },
        { label: "打开申请", moduleId: "archiveResults", query: "打开申请" },
        { label: "禁训区", moduleId: "saas", query: "禁训区" },
        { label: "审计日志", moduleId: "dailyLedger", query: "审计日志 每日台账" },
        { label: "水印策略", moduleId: "downloadGovernance", query: "水印策略" },
        { label: "敏感数字遮盖", moduleId: "downloadGovernance", query: "敏感数字 遮盖 打格子" },
        { label: "下载日报", moduleId: "dailyLedger", query: "下载 日报 台账" },
      ],
    },
    {
      section: "integration",
      title: "平台接口中心",
      hint: "SaaS 集成、Webhook、企微、OA、电子签、对象存储和 Agent",
      items: [
        { label: "企业微信", moduleId: "saas", query: "企业微信" },
        { label: "OA 审批", moduleId: "saas", query: "OA 审批" },
        { label: "飞书/钉钉", moduleId: "saas", query: "飞书 钉钉" },
        { label: "电子签", moduleId: "saas", query: "电子签" },
        { label: "对象存储", moduleId: "saas", query: "对象存储" },
        { label: "云端状态", moduleId: "storageStatus", query: "云端 状态 连接" },
        { label: "Webhook", moduleId: "saas", query: "Webhook" },
        { label: "API 密钥", moduleId: "saas", query: "API 密钥" },
        { label: "Open cloud agent", moduleId: "agentHub", query: "Open cloud agent" },
        { label: "Hermes agent", moduleId: "agentHub", query: "Hermes agent 爱马仕" },
        { label: "回调重试", moduleId: "finishPipeline", query: "回调重试" },
      ],
    },
    {
      section: "agent",
      title: "Agent 接入中心",
      hint: "优先接 Open cloud agent 和 Hermes agent，也允许自定义 Agent",
      items: [
        { label: "Open cloud agent", moduleId: "agentHub", query: "Open cloud agent" },
        { label: "Hermes agent", moduleId: "agentHub", query: "Hermes agent 爱马仕" },
        { label: "自定义 Agent", moduleId: "agentHub", query: "自定义 Agent" },
        { label: "权限令牌", moduleId: "agentHub", query: "权限 令牌" },
        { label: "任务路由", moduleId: "agentHub", query: "任务 路由" },
        { label: "审计回执", moduleId: "agentHub", query: "审计 回执" },
        { label: "失败重试", moduleId: "agentHub", query: "失败 重试" },
      ],
    },
    {
      section: "backup",
      title: "备份与容灾",
      hint: "所有系统都纳入快照、异地、隔离、恢复演练和容灾等级",
      items: [
        { label: "容灾总控", moduleId: "resilience", query: "容灾 总控" },
        { label: "备份快照", moduleId: "resilience", query: "备份快照" },
        { label: "异地备份", moduleId: "resilience", query: "异地备份" },
        { label: "隔离备份", moduleId: "resilience", query: "隔离备份" },
        { label: "批次历史", moduleId: "batchHistory", query: "批次历史" },
        { label: "差异对账", moduleId: "validation", query: "差异对账" },
        { label: "恢复演练", moduleId: "resilience", query: "恢复演练" },
        { label: "健康检查", moduleId: "metrics", query: "健康检查" },
        { label: "存储健康", moduleId: "storageStatus", query: "存储 健康 容量 同步" },
        { label: "合并索引", moduleId: "batchHistory", query: "合并索引" },
      ],
    },
  ],

  moduleCatalog: [
    { id: "command", title: "全域智能检索台", desc: "搜索、语音、一级/二级入口、组织项目字段和文件类型筛选。", defaultSize: "large" },
    { id: "libraryBoard", title: "档案库分类看板", desc: "公司、项目、部门、员工、作品、案例、视频、合同等分类统计。", defaultSize: "wide" },
    { id: "contentDirectory", title: "内容检索总目录", desc: "一级、二级、三级、四级目录树和目录关键词检索。", defaultSize: "large" },
    { id: "metrics", title: "资产指标总览", desc: "文件数量、索引进度、待收尾作品和备份健康。", defaultSize: "wide" },
    { id: "layoutWorkbench", title: "菜单模块编排台", desc: "一级菜单排序、二级材料归属、页面模块顺序、尺寸和锁定。", defaultSize: "wide" },
    { id: "saas", title: "组织架构与权限底座", desc: "公司、项目、部门、个人、作品、模块中心、角色视角和密级权限矩阵。", defaultSize: "large" },
    { id: "fileTypes", title: "电子文件类型库", desc: "照片、声音、视频、邮件、Office、PDF、工程、数据库和备份格式。", defaultSize: "wide" },
    { id: "formulas", title: "Demo 公式样例", desc: "完整度、密级、同步健康和 AI 候选分公式。", defaultSize: "normal" },
    { id: "intake", title: "全介质采集入口", desc: "手机、iPad、旧电脑、邮箱、云盘、NAS、U盘和素材卡。", defaultSize: "large" },
    { id: "storageStatus", title: "存储端点状态看板", desc: "本机、NAS、云端、邮箱、手机、iPad、U盘、SD卡和旧电脑状态。", defaultSize: "wide" },
    { id: "batchHistory", title: "扫描批次历史", desc: "按批次追踪来源、数量、密级、风险和合并索引。", defaultSize: "normal" },
    { id: "validation", title: "真实介质样本验证", desc: "小样本登记、只读试扫、风险复核和扩大接入决策。", defaultSize: "normal" },
    { id: "downloadGovernance", title: "受控下载与外发治理", desc: "本地下载、公司邮箱外发、水印、敏感数字遮盖、多人审批和留痕。", defaultSize: "wide" },
    { id: "dailyLedger", title: "每日台账与行为日报", desc: "查询、申请、审批、下载、访问、修改和 AI 优化全量留痕。", defaultSize: "wide" },
    { id: "archiveResults", title: "档案检索结果与媒体预览", desc: "列表、时间轴、关系图、媒体预览、摘要和复制审批。", defaultSize: "wide" },
    { id: "finishPipeline", title: "AI 收尾池与数据流水线", desc: "待收尾作品、评分中心、自动索引 SOP 和备份快照。", defaultSize: "wide" },
    { id: "resilience", title: "备份容灾总控", desc: "所有系统的快照、异地、隔离、恢复演练和健康检查。", defaultSize: "wide" },
    { id: "agentHub", title: "Agent 接入中心", desc: "Open cloud agent、Hermes agent 和自定义 Agent 接入。", defaultSize: "wide" },
  ],

  menuModuleMap: {
    dashboard: ["command", "libraryBoard", "contentDirectory", "metrics", "storageStatus", "downloadGovernance", "dailyLedger", "layoutWorkbench", "saas", "archiveResults", "finishPipeline"],
    catalog: ["libraryBoard", "contentDirectory", "command", "archiveResults", "fileTypes"],
    layout: ["layoutWorkbench", "command", "saas"],
    tenant: ["saas", "command", "archiveResults"],
    search: ["command", "libraryBoard", "contentDirectory", "archiveResults", "downloadGovernance", "fileTypes"],
    keyword: ["command", "archiveResults", "saas"],
    workType: ["fileTypes", "command", "archiveResults"],
    inbox: ["intake", "storageStatus", "batchHistory", "validation", "downloadGovernance", "archiveResults"],
    media: ["archiveResults", "fileTypes", "formulas"],
    finish: ["finishPipeline", "formulas", "validation", "archiveResults"],
    permission: ["saas", "downloadGovernance", "dailyLedger", "archiveResults", "validation"],
    integration: ["saas", "agentHub", "storageStatus", "finishPipeline", "batchHistory"],
    agent: ["agentHub", "saas", "resilience", "batchHistory"],
    backup: ["resilience", "storageStatus", "finishPipeline", "batchHistory", "validation", "metrics"],
  },

  metrics: [
    { label: "文件总量", value: "9,482,311", note: "今日新增 18,426" },
    { label: "全文索引", value: "68%", note: "OCR 队列 12,304" },
    { label: "待收尾作品", value: "416", note: "S 级 38，A 级 122" },
    { label: "备份健康", value: "97%", note: "最近快照 05:30" },
  ],

  infoTickerCategories: [
    { key: "all", label: "全部" },
    { key: "platform", label: "平台动态" },
    { key: "industry", label: "行业资讯" },
    { key: "enterprise", label: "企业资讯" },
    { key: "job", label: "岗位资讯" },
    { key: "policy", label: "制度资讯" },
  ],

  infoTickerItems: [
    { category: "platform", source: "动态平台", time: "今日 09:00", title: "新增云盘、NAS、邮箱、手机和 U 盘多源接入入口，待授权后进入只读采集流程。" },
    { category: "industry", source: "行业资讯", time: "今日 10:20", title: "数字档案系统建设重点转向 AI 检索、自动摘要、权限留痕和长期备份恢复能力。" },
    { category: "enterprise", source: "企业资讯", time: "今日 11:10", title: "黑卫士四大系统演示入口已整理到桌面统一文件夹，明早可直接打开查看。" },
    { category: "job", source: "岗位资讯", time: "今日 13:30", title: "资料管理员、法务、财务、人事、项目经理和部门负责人将按密级获得不同查看权限。" },
    { category: "policy", source: "制度资讯", time: "今日 15:00", title: "L5/L6 数据导出、镜像回写、完整克隆和容灾热备必须走最高权限多人审批。" },
    { category: "platform", source: "平台动态", time: "今日 16:15", title: "档案卡已加入标题、副标题、简介、作者、创作工具、时间、体量、节点、用途和 AI 评分。" },
    { category: "industry", source: "行业资讯", time: "今日 17:40", title: "企业知识库正从文件夹管理升级为内容画像、语义检索、版本证据链和智能体协作。" },
    { category: "enterprise", source: "公司内部", time: "今日 18:05", title: "内部制度、经典案例、示范文档和高价值半成品将优先进入 AI 补全评分池。" },
  ],

  contentDirectory: [
    {
      level1: "公司与组织",
      icon: "building-2",
      count: "12 类主体",
      children: [
        { level2: "集团公司", level3: "部门建制", level4: "人事/制度/会议/财务" },
        { level2: "项目公司", level3: "项目档案", level4: "启动/执行/收尾/复盘" },
        { level2: "临时项目公司", level3: "授权资料", level4: "合同/邮件/报价/验收" },
      ],
    },
    {
      level1: "业务项目",
      icon: "briefcase-business",
      count: "26 年项目池",
      children: [
        { level2: "发布会/活动", level3: "策划/执行/传播", level4: "方案/PPT/视频/照片" },
        { level2: "移民签证", level3: "客户服务/申请材料", level4: "表格/证明/邮件/合同" },
        { level2: "投标标书", level3: "技术/商务/报价", level4: "标书/附件/澄清/中标" },
      ],
    },
    {
      level1: "内容作品",
      icon: "files",
      count: "成品与半成品",
      children: [
        { level2: "方案提案", level3: "客户提案/内部方案", level4: "经典/优秀/待收尾/残缺" },
        { level2: "媒体资产", level3: "图片/录音/视频", level4: "原片/成片/转写/抽帧" },
        { level2: "制度模板", level3: "惯例制度/经典制度", level4: "示范文档/版本/审批" },
      ],
    },
    {
      level1: "存储来源",
      icon: "database",
      count: "多端归集",
      children: [
        { level2: "NAS/本地/硬盘", level3: "暂存区/正式库/快照区", level4: "只读扫描/校验/归档" },
        { level2: "云端/邮箱/企微", level3: "清单/附件/聊天记录", level4: "下载/镜像/最高授权" },
        { level2: "手机/iPad/U盘/SD卡", level3: "设备/日期/机主", level4: "杀毒/隔离/导入/复核" },
      ],
    },
  ],

  importActionPolicies: [
    { action: "只复制到 NAS 暂存区", permission: "最高授权人审批", virus: "必须查毒", audit: "保留来源、时间、账号和批次" },
    { action: "复制后删除云端原文件", permission: "三名最高授权人共同确认", virus: "必须查毒并隔离风险项", audit: "高风险动作，默认关闭" },
    { action: "复制后镜像回写云端", permission: "三名最高授权人共同确认", virus: "回写前二次查毒", audit: "只允许白名单目录和低密级资料" },
    { action: "仅建立云端清单索引", permission: "系统管理员加负责人确认", virus: "不下载正文，先不查毒", audit: "适合大体量云端先对账" },
  ],

  terminalPorts: [
    { name: "大屏总控端", scope: "总体数据、甘特图、容量、风险、备份健康", permission: "只看总览，不显示高密原文" },
    { name: "管理员端", scope: "索引、批次、权限、备份、Agent 接入", permission: "系统管理员；高危动作需最高授权" },
    { name: "操作终端机", scope: "只读扫描、查毒、入库、点验登记", permission: "操作员；不能删除云端和回写镜像" },
    { name: "iPad 最高权限端", scope: "审批、暂停、授权、容灾确认", permission: "最高授权人；支持三人会签" },
  ],

  storageEndpoints: [
    { name: "NAS 主库", type: "NAS", icon: "server", capacity: "120T", used: "62.4T", health: "98.2%", status: "在线", sync: "主库实时写入", risk: "低", next: "继续快照与哈希抽检" },
    { name: "本机工作盘", type: "本地硬盘", icon: "hard-drive", capacity: "4T", used: "2.1T", health: "96.8%", status: "在线", sync: "只读索引已启用", risk: "低", next: "保留脱敏索引，不暴露完整路径" },
    { name: "公司移动硬盘 A", type: "外接硬盘", icon: "hard-drive", capacity: "8T", used: "6.7T", health: "91.4%", status: "待复核", sync: "清单已生成", risk: "中", next: "先查毒，再决定是否复制到 NAS 暂存区" },
    { name: "iCloud 企业资料", type: "云端云盘", icon: "cloud", capacity: "2T", used: "1.3T", health: "88.6%", status: "待授权", sync: "只拉清单，不下载正文", risk: "中高", next: "配置账号授权和下载边界" },
    { name: "企业邮箱归档", type: "邮箱库", icon: "mail", capacity: "860G", used: "412G", health: "84.0%", status: "待授权", sync: "邮件与附件分开归集", risk: "高", next: "先导出清单，合同/人事/财务默认隔离" },
    { name: "离职员工手机样本", type: "手机", icon: "smartphone", capacity: "512G", used: "381G", health: "79.5%", status: "待点验", sync: "照片/视频/聊天导出待授权", risk: "高", next: "确认机主、时间段、隐私排除和人脸识别授权" },
    { name: "iPad 会议资料", type: "iPad", icon: "tablet", capacity: "256G", used: "142G", health: "93.1%", status: "在线", sync: "会议文件进入平板暂存区", risk: "中", next: "优先 OCR 手写批注和会议附件" },
    { name: "U盘临时交接", type: "U盘", icon: "usb", capacity: "128G", used: "96G", health: "75.2%", status: "隔离检查", sync: "禁止直接入正式库", risk: "高", next: "查毒、重复检查、来源登记后再申请入库" },
  ],

  downloadDestinations: [
    { name: "下载到本地电脑", icon: "hard-drive", scope: "仅允许进入受控下载目录，文件名带申请编号和水印编号", approval: "所有下载至少 3 人审批", watermark: "默认添加姓名、账号、时间、IP、MAC、文件编号水印", status: "可申请" },
    { name: "发送到公司指定工作邮箱", icon: "mail", scope: "只允许发送到公司备案邮箱，不允许私人邮箱", approval: "外发视同下载，至少 3 人审批", watermark: "正文和附件都加外发水印，邮件台账必须记录收件地址", status: "可申请" },
    { name: "最高权限资料下载", icon: "shield-check", scope: "L5/L6、容灾包、克隆机、完整数据库和组织架构备份", approval: "至少 2 名最高授权人共同审批", watermark: "强水印、隐藏指纹、敏感数字遮盖，必要时只给脱敏副本", status: "最高权限" },
    { name: "管理权限资料下载", icon: "git-branch", scope: "部门级批量资料、审批链、管理报表和跨部门材料", approval: "至少 3 名管理权限审批人共同审批", watermark: "管理水印、访问目的、审批链编号和有效期", status: "管理审批" },
  ],

  downloadProtectionRules: [
    { level: "L0 外部流通", watermark: "轻水印", masking: "不默认遮盖", approval: "按公开资料流程，可记录台账", note: "仍记录下载人和用途" },
    { level: "L1 普通", watermark: "标准水印", masking: "合同编号和手机号可选遮盖", approval: "按部门规则审批", note: "可下载到本地受控目录" },
    { level: "L2 内部", watermark: "标准水印 + 账号指纹", masking: "客户电话、邮箱、身份证局部遮盖", approval: "至少 3 人审批", note: "禁止私人邮箱外发" },
    { level: "L3 敏感", watermark: "受控水印", masking: "金额、证件号、银行卡、手机号打格子", approval: "至少 3 人审批", note: "外发必须走公司邮箱" },
    { level: "L4 机密", watermark: "强水印 + 隐藏指纹", masking: "敏感数字默认打格子，只展示必要字段", approval: "至少 3 人审批并法务留痕", note: "优先给脱敏副本" },
    { level: "L5 最高授权", watermark: "最高权限强水印", masking: "敏感数字、客户身份、金额和账号默认遮盖", approval: "至少 2 名最高授权人审批", note: "默认不可批量下载" },
    { level: "L6 绝密", watermark: "绝密水印 + 逐页指纹", masking: "默认只给脱敏摘要，原文不得外发", approval: "至少 2 名最高授权人审批并记录原因", note: "必要时只允许在线查看" },
  ],

  sensitiveMaskRules: [
    { target: "手机号/邮箱/身份证", method: "局部遮盖", demo: "138****8866 / z***@company.com / 4403**********1234" },
    { target: "银行卡/账号/税号", method: "打格子", demo: "6222 □□□□ □□□□ 7788 / 纳税号分段遮盖" },
    { target: "金额/报价/预算", method: "按权限显示", demo: "低权限显示为 □□□,□□□ 元；审批后显示完整值" },
    { target: "客户名称/联系人", method: "脱敏副本", demo: "客户 A / 联系人 B，仅最高授权可回看原文" },
    { target: "下载副本指纹", method: "隐藏水印", demo: "写入申请编号、审批链编号、下载时间和设备指纹" },
  ],

  dailyLedgerSummary: [
    { label: "今日查询", value: "286", note: "含单一检索 198、联合检索 88" },
    { label: "下载/外发申请", value: "17", note: "本地下载 11、工作邮箱外发 6" },
    { label: "审批动作", value: "43", note: "通过 31、退回 8、升级 4" },
    { label: "高敏拦截", value: "9", note: "L4-L6、敏感数字未遮盖或审批不足" },
  ],

  dailyLedgerItems: [
    { time: "09:12", actor: "孙博文", account: "sunbowen@company.com", face: "人脸通过", device: "MacBook-Pro-17", mac: "8C:85:90:2A:xx:41", ip: "192.168.1.42", action: "联合检索", target: "2024 发布会 + 广告公司 + 视频", url: "内网检索入口", approver: "无需审批", result: "已留痕" },
    { time: "10:06", actor: "陈项目", account: "pm.chen@company.com", face: "人脸通过", device: "iPad 最高权限端", mac: "A4:5E:60:11:xx:09", ip: "192.168.1.88", action: "申请下载", target: "体育赛事投标文件 L3", url: "本地受控下载目录", approver: "部门负责人/法务/系统管理员", result: "审批中" },
    { time: "11:28", actor: "法务审计", account: "audit@company.com", face: "人脸复核", device: "管理员端", mac: "F0:18:98:76:xx:13", ip: "10.0.0.25", action: "审批外发", target: "客户往来邮件附件", url: "公司指定工作邮箱", approver: "法务审计", result: "通过，强水印" },
    { time: "13:40", actor: "资料管理员", account: "archive.ops@company.com", face: "人脸通过", device: "操作终端机", mac: "70:9C:D1:33:xx:65", ip: "192.168.1.61", action: "敏感遮盖", target: "合同金额和客户证件号", url: "脱敏副本生成区", approver: "系统规则", result: "已打格子" },
    { time: "15:05", actor: "最高授权人 A", account: "owner.a@company.com", face: "人脸通过", device: "iPad 最高权限端", mac: "34:AB:37:56:xx:20", ip: "192.168.1.90", action: "最高权限审批", target: "L5 财务汇总表", url: "在线查看，不外发", approver: "最高授权人 A/B", result: "等待第二人" },
  ],

  resiliencePlans: [
    { name: "时间胶囊备份", icon: "history", scope: "按小时/天/月保留关键索引、配置、目录和批次快照", permission: "最高权限", approval: "三名最高授权人会签", status: "建议启用" },
    { name: "完整备份", icon: "archive", scope: "主库文件、索引、批次报告、脱敏清单整体备份", permission: "最高权限", approval: "三名最高授权人会签", status: "定期执行" },
    { name: "数据库备份", icon: "database-backup", scope: "元数据、权限、审计、目录树、评分和索引库", permission: "最高权限", approval: "三名最高授权人会签", status: "高频执行" },
    { name: "组织架构备份", icon: "network", scope: "公司、部门、员工、岗位、负责人和权限矩阵", permission: "最高权限", approval: "三名最高授权人会签", status: "变更即备份" },
    { name: "节点协议端口备份", icon: "router", scope: "NAS、云端、邮箱、企微、Agent、Webhook 的协议和端口配置", permission: "最高权限", approval: "三名最高授权人会签", status: "加密封存" },
    { name: "完整克隆机备份", icon: "server-cog", scope: "可接管生产系统的备用主机、服务配置和恢复脚本", permission: "最高最高权限", approval: "三名最高授权人同时同意", status: "只在演练窗口执行" },
  ],

  agentConnectors: [
    { name: "Open cloud agent", icon: "cloud-cog", priority: "优先推荐", role: "云端任务、跨系统同步、长任务调度", permission: "最高授权后启用", status: "待配置" },
    { name: "Hermes agent", icon: "send", priority: "优先推荐", role: "飞书/消息通知、进度战报、停顿提醒", permission: "需要 webhook/token", status: "飞书通道待配置" },
    { name: "自定义 Agent", icon: "bot", priority: "可扩展", role: "OCR、转写、查毒、审计、备份、归档等专项任务", permission: "按模块授权", status: "预留接入" },
  ],

  intakeSources: [
    {
      key: "mobile",
      icon: "smartphone",
      name: "手机",
      examples: "iPhone、安卓手机、微信/相册/文件App",
      access: "数据线、局域网投递、云端同步目录",
      target: "NAS 手机暂存区",
      status: "优先接入",
      risk: "中高",
      batchPrefix: "MOB",
      scanScope: "照片、视频、录音、聊天导出、文件 App 目录",
      securityDefault: "L3 敏感候选",
      precheck: "确认机主、时间段、隐私范围和是否允许导出",
      report: "设备清单、照片视频数量、文件大小、修改时间、重复候选",
      nasGate: "授权后进入 NAS 手机暂存区，按机主和日期保留原结构",
      aiGate: "L0-L2 可进 OCR/转写候选；照片人脸识别必须单独授权",
      next: "先采集照片、视频、录音、聊天导出和文件夹",
    },
    {
      key: "tablet",
      icon: "tablet",
      name: "iPad/平板",
      examples: "iPad、安卓平板、手写稿、会议资料",
      access: "数据线、AirDrop、同步目录",
      target: "NAS 平板暂存区",
      status: "优先接入",
      risk: "中",
      batchPrefix: "TAB",
      scanScope: "文档、图片、批注稿、会议资料、手写稿",
      securityDefault: "L2 内部候选",
      precheck: "确认设备主人、应用来源、会议资料范围",
      report: "文档类型、批注文件、图片数量、修改时间和重复候选",
      nasGate: "授权后进入 NAS 平板暂存区，保留应用导出结构",
      aiGate: "会议资料和手写稿先 OCR 候选，高密级不进训练",
      next: "重点采集文档、图片、批注稿和会议资料",
    },
    {
      key: "old-computer",
      icon: "monitor",
      name: "旧电脑/不同主机",
      examples: "旧 Mac、Windows、服务器、员工电脑",
      access: "局域网共享、远程索引、移动硬盘中转",
      target: "NAS 主机暂存区",
      status: "分批接入",
      risk: "中",
      batchPrefix: "PC",
      scanScope: "桌面、文档、项目盘、历史客户资料、软件工程目录",
      securityDefault: "L2 内部候选",
      precheck: "登记主机编号、使用人、系统类型、隐私排除目录",
      report: "主机文件总量、目录分布、格式分布、敏感候选和不可读目录",
      nasGate: "先只读扫描；授权后按主机编号进入 NAS 主机暂存区",
      aiGate: "项目文档可进候选；个人隐私、账号、密钥和高密级资料禁训",
      next: "先按电脑编号只读扫描，再汇总索引",
    },
    {
      key: "email",
      icon: "mail",
      name: "邮箱",
      examples: "企业邮箱、个人邮箱、163、139、Gmail、历史客户邮件",
      access: "邮箱导出、EML/MSG、MBOX、授权 API",
      target: "NAS 邮件暂存区",
      status: "待授权",
      risk: "高",
      batchPrefix: "MAIL",
      scanScope: "邮件包、EML/MSG、附件、客户往来记录",
      securityDefault: "L3 敏感候选",
      precheck: "确认邮箱账号、时间范围、客户范围和附件导出范围",
      report: "邮件数量、发件人、收件人、时间段、附件数量、敏感词命中",
      nasGate: "授权后邮件和附件分开入 NAS 邮件暂存区，保留原邮件来源",
      aiGate: "附件可 OCR 候选；客户隐私、合同、人事、财务邮件默认禁训",
      next: "先导出邮件清单和附件索引，敏感邮件不进训练",
    },
    {
      key: "wechat-work",
      icon: "messages-square",
      name: "企业微信/离职数据",
      examples: "企微会话、客户群、离职员工交接、企业文档",
      access: "企业后台导出、合规存档接口、授权 API",
      target: "NAS 企微暂存区",
      status: "最高授权",
      risk: "高",
      batchPrefix: "WXWORK",
      scanScope: "会话清单、附件、客户群文件、离职交接资料",
      securityDefault: "L4 机密候选",
      precheck: "确认企业授权、员工范围、客户范围、时间段和合规边界",
      report: "会话数量、附件数量、客户范围、敏感词命中和不可导出项",
      nasGate: "授权后进入 NAS 企微暂存区，客户隐私默认隔离",
      aiGate: "默认禁训；只允许脱敏摘要进入 AI 候选",
      next: "先导出清单，再由最高授权人决定是否拉取附件",
    },
    {
      key: "cloud",
      icon: "cloud",
      name: "云端云盘/公有云",
      examples: "iCloud、华为云、163、139、Google Drive、Meta、OneDrive、百度网盘、阿里云盘、对象存储",
      access: "同步目录、云端清单、API",
      target: "NAS 云盘暂存区",
      status: "清单优先",
      risk: "中高",
      batchPrefix: "CLOUD",
      scanScope: "同步目录、云端清单、共享文件夹、对象存储清单",
      securityDefault: "L2 内部候选",
      precheck: "确认云盘账号、共享范围、同步方向、下载成本、删除/镜像权限",
      report: "云端清单、本机同步差异、缺失文件、重复文件、版本冲突",
      nasGate: "先清单对账；授权后热数据进入 NAS 云盘暂存区",
      aiGate: "只允许 L0-L2 或已授权资料进入 AI 候选",
      next: "先清单对账；只复制、复制后删除、镜像回写都必须分权限审批",
    },
    {
      key: "nas",
      icon: "server",
      name: "NAS 总库",
      examples: "群晖、QNAP、TrueNAS、文件服务器",
      access: "SMB/AFP/NFS/API",
      target: "最终归总主库",
      status: "核心目标",
      risk: "中",
      batchPrefix: "NAS",
      scanScope: "暂存区、正式库、快照区、禁训区、部门共享区",
      securityDefault: "按目录继承密级",
      precheck: "确认共享协议、账号权限、快照策略和禁训区边界",
      report: "NAS 清单、卷容量、权限目录、快照状态、差异对账",
      nasGate: "NAS 本身是归总主库，先分暂存区和正式库",
      aiGate: "禁训区不进入 AI；L4-L6 仅本机/NAS 受控索引",
      next: "建立暂存区、正式库、快照区和禁训区",
    },
    {
      key: "usb",
      icon: "usb",
      name: "U盘/移动硬盘",
      examples: "客户拷贝盘、临时交接盘、移动 SSD",
      access: "本机挂载、只读扫描",
      target: "NAS 外接盘暂存区",
      status: "随到随扫",
      risk: "中高",
      batchPrefix: "USB",
      scanScope: "移动硬盘、U盘、客户交接盘、临时拷贝盘",
      securityDefault: "L2 内部候选",
      precheck: "确认来源人、用途、是否查毒、是否允许拷贝",
      report: "卷名、文件数量、格式分布、重复候选、风险文件和读取失败",
      nasGate: "先只读扫描；授权后进入 NAS 外接盘暂存区",
      aiGate: "只允许低密级成品进入候选；未知来源文件先隔离",
      next: "先查病毒和重复，再拷贝授权资料",
    },
    {
      key: "sd-card",
      icon: "sd-card",
      name: "SD卡/存储卡",
      examples: "相机卡、摄像机卡、录音笔卡",
      access: "读卡器、本机挂载",
      target: "NAS 素材暂存区",
      status: "优先保护",
      risk: "高",
      batchPrefix: "CARD",
      scanScope: "照片原片、视频原片、录音、卡内 DCIM 和设备目录",
      securityDefault: "L2 内部候选",
      precheck: "确认拍摄项目、拍摄日期、卡状态和是否先做镜像",
      report: "素材数量、拍摄时间、大小、卡结构、读取失败和重复候选",
      nasGate: "先镜像保护，再进入 NAS 素材暂存区",
      aiGate: "抽帧、转写、人脸识别候选必须在授权后执行",
      next: "先镜像备份，再抽帧、转写、人脸识别候选",
    },
    {
      key: "camera",
      icon: "camera",
      name: "相机/摄像机",
      examples: "单反、微单、运动相机、摄像机",
      access: "数据线、读卡器、采集站",
      target: "NAS 影像暂存区",
      status: "素材优先",
      risk: "中高",
      batchPrefix: "CAM",
      scanScope: "相机照片、视频、工程文件、代理文件、拍摄日期目录",
      securityDefault: "L2 内部候选",
      precheck: "确认设备、拍摄项目、素材范围和是否保留原文件名",
      report: "照片视频数量、格式、拍摄时间、设备目录和重复候选",
      nasGate: "授权后进入 NAS 影像暂存区，保留原始拍摄结构",
      aiGate: "抽帧和人脸识别必须走授权；原始素材不上传公有云",
      next: "采集照片、原片、成片、工程文件和拍摄日期",
    },
  ],

  intakeWorkflow: [
    { step: "01", title: "来源登记", detail: "记录来源、负责人、批次编号、默认密级和授权边界" },
    { step: "02", title: "扫描前确认", detail: "确认设备状态、样本目录、隐私排除、高密级候选和只读原则" },
    { step: "03", title: "只读采集", detail: "先做清单、路径、大小、修改时间，不移动、不删除、不改名" },
    { step: "04", title: "扫描报告", detail: "输出数量、体积、格式分布、敏感候选、重复候选和读取失败" },
    { step: "05", title: "NAS/AI 分流", detail: "授权资料进 NAS 暂存区；低密级资料再进入 OCR、转写、抽帧候选" },
  ],

  sampleValidationChecklist: [
    {
      step: "01",
      title: "接入前登记",
      owner: "项目负责人",
      gate: "确认来源人、设备类型、公司/部门/项目、默认密级和授权范围",
      output: "样本批次编号、来源说明、隐私排除目录、负责人",
    },
    {
      step: "02",
      title: "只读试扫",
      owner: "技术/档案管理员",
      gate: "只扫描 1 个小目录或 1 个设备样本，不移动、不删除、不改名",
      output: "文件数量、体积、格式分布、不可读条目、耗时记录",
    },
    {
      step: "03",
      title: "风险复核",
      owner: "部门负责人",
      gate: "检查 L4-L6、财务、人事、合同、隐私、密钥、未知来源文件",
      output: "禁训清单、隔离候选、高密级候选、人工复核意见",
    },
    {
      step: "04",
      title: "批次报告",
      owner: "档案管理员",
      gate: "确认批次摘要、批次历史、合并索引和浏览器脱敏索引一致",
      output: "批次报告、脱敏页面数据、合并索引摘要",
    },
    {
      step: "05",
      title: "NAS/AI 分流",
      owner: "最高授权人/系统管理员",
      gate: "授权后才进入 NAS 暂存区；L4-L6 不进公有云、不进 AI 训练",
      output: "NAS 暂存位置、AI 候选清单、禁训清单",
    },
    {
      step: "06",
      title: "扩大接入",
      owner: "项目主理人",
      gate: "样本验证通过后，按公司、部门、年份或设备分批扩大",
      output: "下一批扫描范围、预计体量、负责人、回滚方案",
    },
  ],

  sampleValidationFields: [
    { label: "样本来源类型", value: "硬盘 / NAS / 手机 / 云盘 / U盘 / SD卡 / 相机 / 邮箱" },
    { label: "来源名称", value: "设备编号、卷名、云盘账号或邮箱账号" },
    { label: "公司/部门/项目", value: "所属公司、部门、项目名称，允许临时项目公司" },
    { label: "负责人", value: "项目主理人、经办人、部门负责人、最高授权人" },
    { label: "样本范围", value: "先选 1 个小目录、1 个日期段或 1 个设备样本" },
    { label: "模糊时间段", value: "如 2018-2020、2024 年会、项目筹备期到收尾期" },
    { label: "隐私排除", value: "个人相册、账号密码、密钥、私人聊天、非授权客户资料" },
    { label: "默认密级", value: "默认 L2/L3；发现 L4-L6 立即标记禁训和人工复核" },
    { label: "扫描方式", value: "只读扫描；不移动、不删除、不改名真实文件" },
    { label: "NAS 暂存位置", value: "按来源类型、负责人、日期、批次编号进入暂存区" },
    { label: "AI 候选边界", value: "L0-L2 可候选；L3 授权后候选；L4-L6 禁止训练" },
    { label: "验收结果", value: "通过、待补充、隔离、暂停、扩大下一批" },
  ],

  samplePreflightChecks: [
    { title: "只读原则", detail: "确认本轮只建立索引和报告，不移动、不删除、不改名真实文件。", status: "必须通过" },
    { title: "来源授权", detail: "确认来源人、负责人、公司/部门/项目、授权范围和隐私排除项。", status: "必须通过" },
    { title: "样本范围", detail: "先选小目录、日期段或单设备样本，不直接扫描整块 40T-60T。", status: "必须通过" },
    { title: "空间与备份", detail: "确认本机/NAS 有足够索引空间；扫描前不复制大文件，先备份小索引。", status: "必须通过" },
    { title: "安全风险", detail: "未知 U盘、旧电脑、邮件附件先标风险；高风险文件不进入正式库。", status: "人工复核" },
    { title: "密级禁训", detail: "L4-L6、财务、人事、合同、隐私、密钥默认进入禁训和人工复核。", status: "人工复核" },
    { title: "路径脱敏", detail: "浏览器只显示相对路径和编号；本机完整路径只留在本地服务端。", status: "必须通过" },
    { title: "负责人签字", detail: "扫描报告、批次摘要、下一批范围必须由负责人确认。", status: "必须通过" },
  ],

  sampleResultDecisionTitle: "点验结果判定表",
  sampleResultDecisions: [
    { result: "通过", next: "进入下一批只读扫描", rule: "报告完整、路径脱敏、无高风险阻塞、负责人确认。", color: "go" },
    { result: "待补充", next: "补登记或补授权", rule: "来源、负责人、项目、时间段、隐私排除或密级信息不完整。", color: "wait" },
    { result: "隔离", next: "进入隔离候选区", rule: "未知来源、疑似病毒、密钥、账号、合同、人事或财务高敏候选。", color: "hold" },
    { result: "暂停", next: "停止扩大扫描", rule: "发现权限不清、路径暴露、读取异常集中或负责人未确认。", color: "stop" },
    { result: "扩大下一批", next: "按公司/部门/年份/设备扩展", rule: "样本稳定、分类准确、风险可控、NAS/AI 分流边界明确。", color: "go" },
  ],

  fieldSearches: [
    { field: "companyType", label: "公司类型", placeholder: "如：项目公司、集团公司" },
    { field: "project", label: "项目名称", placeholder: "如：汽车品牌发布会" },
    { field: "projectType", label: "项目类型", placeholder: "如：投标、年会、述职" },
    { field: "company", label: "公司名称", placeholder: "如：广告公司" },
    { field: "departmentSystem", label: "部门建制", placeholder: "如：集团法务、营销中心" },
    { field: "department", label: "部门名称", placeholder: "如：策划部" },
    { field: "employee", label: "员工姓名", placeholder: "作者/负责人/参与人" },
    { field: "functionRole", label: "人事/职能", placeholder: "如：文案、顾问、剪辑" },
    { field: "periodSearchText", label: "周期阶段", placeholder: "如：2016到2019、Q1、筹备期" },
    { field: "assetStage", label: "完整状态", placeholder: "残缺、完整、待补充" },
    { field: "qualityLevel", label: "作品等级", placeholder: "优质、经典案例、示范文档" },
    { field: "level", label: "密级", placeholder: "L0、L3、L6" },
    { field: "storageSourceType", label: "存储来源", placeholder: "本机、云盘、NAS、U盘" },
    { field: "storageProvider", label: "存储名称", placeholder: "iCloud、NAS、移动硬盘" },
    { field: "accessMode", label: "接入方式", placeholder: "本机直连、同步目录、SMB" },
    { field: "syncStrategy", label: "同步策略", placeholder: "云本同步、只读索引、三方校验" },
    { field: "syncStatus", label: "同步状态", placeholder: "已同步、待校验、离线" },
    { field: "crossCheckPolicy", label: "交叉校验", placeholder: "清单、大小、哈希、差异报告" },
    { field: "storageRisk", label: "存储风险", placeholder: "低、中、中高、高" },
    { field: "storageCostLevel", label: "成本等级", placeholder: "低、中、中高、高" },
  ],

  workTypes: [
    { key: "all", icon: "layers", label: "全部类型", active: true },
    { key: "image", icon: "image", label: "照片/图片/JPG/PNG/HEIC/RAW" },
    { key: "video", icon: "video", label: "视频/MP4/MOV/AVI/MKV" },
    { key: "audio", icon: "audio-lines", label: "录音/MP3/WAV/M4A/AAC" },
    { key: "email", icon: "mail", label: "邮件/EML/MSG/附件" },
    { key: "contract", icon: "file-signature", label: "合同/协议/电子签" },
    { key: "proposal", icon: "clipboard-list", label: "方案/提案/策划" },
    { key: "bid", icon: "briefcase-business", label: "标书/投标/招采" },
    { key: "ppt", icon: "presentation", label: "PPT/PPTX/KEY" },
    { key: "word", icon: "file-text", label: "Word/DOC/DOCX/TXT/RTF" },
    { key: "excel", icon: "table-2", label: "Excel/XLS/XLSX/CSV" },
    { key: "pdf", icon: "file-type", label: "PDF/OFD/电子发票" },
    { key: "scan", icon: "scan-text", label: "扫描件/OCR/TIFF" },
    { key: "logo", icon: "badge-check", label: "标识/LOGO/VI" },
    { key: "design", icon: "palette", label: "画册/PSD/AI/CDR/Figma" },
    { key: "code", icon: "code-2", label: "程序/代码/脚本" },
    { key: "database", icon: "database", label: "数据库/SQL/JSON/XML" },
    { key: "archive", icon: "package", label: "压缩包/ZIP/RAR/7Z/备份" },
    { key: "cad", icon: "drafting-compass", label: "CAD/工程图/DWG/DXF" },
    { key: "chat", icon: "messages-square", label: "聊天记录/微信/企微" },
  ],

  quickFilters: [
    { key: "all", label: "全部", active: true },
    { key: "finish", label: "待收尾" },
    { key: "classic", label: "经典案例" },
    { key: "audio", label: "录音转写" },
    { key: "video", label: "视频" },
    { key: "private", label: "高密级" },
  ],

  roles: [
    {
      key: "owner",
      name: "最高授权人",
      scope: "全集团、全项目、全密级",
      can: ["查看 L0-L6", "授权复制/打开", "配置模块", "查看审计", "启停 AI 候选"],
      blocked: ["无"],
    },
    {
      key: "admin",
      name: "系统管理员",
      scope: "系统配置、索引、备份和接口",
      can: ["配置模块", "管理索引", "查看 L0-L4", "处理备份", "接口联调"],
      blocked: ["不能绕过最高授权复制 L5-L6", "不能查看禁训正文"],
    },
    {
      key: "manager",
      name: "部门负责人",
      scope: "本公司、本部门、本项目",
      can: ["查看 L0-L3", "审批部门资料", "查看部门统计", "发起补全任务"],
      blocked: ["跨部门敏感资料", "L4-L6 原文", "系统级模块配置"],
    },
    {
      key: "staff",
      name: "员工/作者",
      scope: "本人创建、本人参与和公开资料",
      can: ["查看 L0-L2", "提交资料", "补充标签", "申请打开"],
      blocked: ["他人私密资料", "合同/财务/人事敏感原文", "导出批量数据"],
    },
    {
      key: "auditor",
      name: "审计/法务",
      scope: "审计日志、合同、审批和留痕",
      can: ["查看审批链", "查看水印记录", "抽查 L0-L4", "冻结资料"],
      blocked: ["业务无关个人资料", "删除资料", "修改历史索引"],
    },
  ],

  modules: [
    { key: "tenant", icon: "building-2", title: "公司组织架构", desc: "集团公司、项目公司、部门、岗位、成员和人员关系可配置。", enabled: true, plan: "平台底座" },
    { key: "archive", icon: "folder-search", title: "数字档案主库", desc: "本机、NAS、云盘、外接盘统一索引。", enabled: true, plan: "核心模块" },
    { key: "permission", icon: "shield-check", title: "权限与审计", desc: "角色、密级、复制审批、打开申请和水印留痕。", enabled: true, plan: "核心模块" },
    { key: "ai", icon: "brain-circuit", title: "AI OCR/转写/摘要", desc: "低密级自动候选，高密级走授权和禁训。", enabled: true, plan: "AI 模块" },
    { key: "media", icon: "play-square", title: "媒体中心", desc: "照片、视频、声音、转写、抽帧和素材版本。", enabled: true, plan: "内容模块" },
    { key: "workflow", icon: "git-branch", title: "审批工作流", desc: "复制、导出、移动、补全、归档都可配置流程。", enabled: true, plan: "SaaS 能力" },
    { key: "integration", icon: "blocks", title: "平台接口中心", desc: "企微、OA、飞书、电子签、Webhook、对象存储。", enabled: true, plan: "接口模块" },
    { key: "billing", icon: "receipt", title: "版本/容量控制", desc: "按公司、空间、AI 用量、模块启用控制版本。", enabled: false, plan: "预留模块" },
  ],

  permissionMatrix: [
    { action: "全域搜索", owner: "允许", admin: "允许", manager: "部门内", staff: "本人/公开", auditor: "审计范围" },
    { action: "打开原文件", owner: "允许", admin: "申请", manager: "申请", staff: "申请", auditor: "只读抽查" },
    { action: "复制/导出", owner: "允许", admin: "申请", manager: "审批后", staff: "禁止批量", auditor: "留痕导出" },
    { action: "L4-L6 高密资料", owner: "允许", admin: "元数据", manager: "不可见", staff: "不可见", auditor: "审批抽查" },
    { action: "AI 训练候选", owner: "配置", admin: "执行", manager: "建议", staff: "提交", auditor: "审计" },
    { action: "模块开关", owner: "允许", admin: "允许", manager: "不可改", staff: "不可改", auditor: "只读" },
  ],

  fileTypeGroups: [
    { title: "图片与设计", items: ["JPG", "JPEG", "PNG", "HEIC", "WEBP", "GIF", "TIFF", "RAW", "PSD", "AI", "CDR", "SVG", "FIG", "SKETCH"] },
    { title: "声音与视频", items: ["MP3", "WAV", "M4A", "AAC", "FLAC", "AMR", "MP4", "MOV", "AVI", "MKV", "WMV", "MTS", "SRT"] },
    { title: "办公文档", items: ["DOC", "DOCX", "WPS", "TXT", "RTF", "PPT", "PPTX", "KEY", "XLS", "XLSX", "CSV", "NUMBERS"] },
    { title: "版式与扫描", items: ["PDF", "OFD", "CAJ", "TIFF", "JPG 扫描", "OCR 文本", "电子发票", "电子签章"] },
    { title: "邮件与沟通", items: ["EML", "MSG", "MBOX", "邮件附件", "微信导出", "企微记录", "聊天截图", "会议纪要"] },
    { title: "工程与数据", items: ["DWG", "DXF", "BIM", "SQL", "DB", "SQLite", "JSON", "XML", "YAML", "LOG", "MD"] },
    { title: "系统与备份", items: ["ZIP", "RAR", "7Z", "TAR", "DMG", "ISO", "BAK", "快照", "哈希清单", "Manifest"] },
  ],

  formulaExamples: [
    { title: "作品完整度", formula: "完整度 = 必填页命中率 40% + 附件齐套率 30% + 版本闭环 20% + 人工确认 10%", sample: "发布会方案缺预算页和复盘页，完整度 78 分，进入待补全池。" },
    { title: "密级建议", formula: "密级 = 内容敏感度 + 人事/财务/合同命中 + 客户隐私 + 来源风险", sample: "合同 + 客户姓名 + 金额命中，默认 L4，禁止 AI 训练。" },
    { title: "同步健康", formula: "健康度 = 文件数量一致 35% + 大小一致 25% + 修改时间一致 20% + 哈希抽检 20%", sample: "NAS 与本机索引 97% 一致，3 个目录待复核。" },
    { title: "AI 候选分", formula: "候选分 = 低密级 30% + OCR 可读 25% + 业务价值 25% + 重复度低 20%", sample: "PPT 提案 L2、文字可读、评分 A，进入摘要候选。" },
  ],

  tableColumns: [
    { key: "title", label: "标题" },
    { key: "project", label: "项目名称" },
    { key: "projectType", label: "项目类型" },
    { key: "company", label: "公司" },
    { key: "companyType", label: "公司类型" },
    { key: "department", label: "部门" },
    { key: "author", label: "员工/作者" },
    { key: "owner", label: "负责人" },
    { key: "ownerLevel", label: "负责人等级" },
    { key: "functionRole", label: "职能" },
    { key: "period", label: "周期" },
    { key: "periodSearchText", label: "周期阶段" },
    { key: "workType", label: "作品类型" },
    { key: "assetStage", label: "完整状态" },
    { key: "qualityLevel", label: "作品等级" },
    { key: "format", label: "格式" },
    { key: "storageSourceType", label: "存储来源" },
    { key: "storageProvider", label: "存储名称" },
    { key: "accessMode", label: "接入方式" },
    { key: "syncStrategy", label: "同步策略" },
    { key: "syncStatus", label: "同步状态" },
    { key: "storageRisk", label: "存储风险" },
    { key: "storageCostLevel", label: "成本等级" },
    { key: "status", label: "状态" },
    { key: "completionScore", label: "完成度" },
    { key: "qualityScore", label: "水准" },
    { key: "selfCheckScore", label: "自检" },
    { key: "aiRepairLabel", label: "AI 修复" },
    { key: "level", label: "密级" },
  ],

  appearance: {
    palettes: [
      {
        key: "hws-steady",
        label: "黑卫士中绿",
        accent: "#00875a",
        accentSoft: "#e1f4ea",
        sidebar: "#0b4b3f",
        sidebarActive: "#0b7355",
        page: "#f1f6f2",
      },
      {
        key: "tencent-green",
        label: "腾讯绿",
        accent: "#07c160",
        accentSoft: "#e5f8ee",
        sidebar: "#073b2f",
        sidebarActive: "#0a7a4d",
        page: "#f3f8f5",
      },
      {
        key: "hws-bluegreen",
        label: "黑卫士蓝绿",
        accent: "#0f766e",
        accentSoft: "#dff4ef",
        sidebar: "#0b2638",
        sidebarActive: "#123f53",
        page: "#eef4f6",
      },
      {
        key: "office-blue",
        label: "App Store 蓝",
        accent: "#0a84ff",
        accentSoft: "#e7f2ff",
        sidebar: "#09243a",
        sidebarActive: "#0b4f8a",
        page: "#f3f8ff",
      },
      {
        key: "ink-gray",
        label: "黑白灰",
        accent: "#334155",
        accentSoft: "#eef2f7",
        sidebar: "#ffffff",
        sidebarActive: "#f1f5f9",
        page: "#f6f7f9",
      },
      {
        key: "warm-green",
        label: "柔和浅绿",
        accent: "#16803c",
        accentSoft: "#e8f7ee",
        sidebar: "#ffffff",
        sidebarActive: "#edf9f2",
        page: "#f4f8f5",
      },
    ],
    fonts: [
      {
        key: "yahei",
        label: "微软雅黑",
        value: '"Microsoft YaHei", "PingFang SC", "Noto Sans CJK SC", Arial, sans-serif',
      },
      {
        key: "heiti",
        label: "黑体",
        value: '"Heiti SC", "SimHei", "Microsoft YaHei", Arial, sans-serif',
      },
      {
        key: "youyuan",
        label: "幼圆",
        value: '"YouYuan", "YouYuan SC", "Microsoft YaHei", Arial, sans-serif',
      },
      {
        key: "pingfang",
        label: "苹方",
        value: '"PingFang SC", "Microsoft YaHei", "Noto Sans CJK SC", Arial, sans-serif',
      },
    ],
    fontSize: {
      default: 15,
      min: 13,
      max: 18,
    },
  },
};
