window.HWS_ARCHIVE_CONFIG = {
  navItems: [
    { section: "dashboard", icon: "layout-dashboard", label: "大屏首页", active: true },
    { section: "search", icon: "search", label: "智能检索" },
    { section: "keyword", icon: "building-2", label: "项目/组织/人员检索" },
    { section: "workType", icon: "files", label: "作品类型检索" },
    { section: "inbox", icon: "hard-drive", label: "资料入库" },
    { section: "media", icon: "play-square", label: "媒体中心" },
    { section: "finish", icon: "sparkles", label: "待收尾作品池" },
    { section: "authors", icon: "pen-tool", label: "作者中心" },
    { section: "ai", icon: "brain-circuit", label: "AI 知识库" },
    { section: "approval", icon: "shield-check", label: "审批权限" },
    { section: "backup", icon: "database-backup", label: "备份中心" },
  ],

  metrics: [
    { label: "文件总量", value: "9,482,311", note: "今日新增 18,426" },
    { label: "全文索引", value: "68%", note: "OCR 队列 12,304" },
    { label: "待收尾作品", value: "416", note: "S 级 38，A 级 122" },
    { label: "备份健康", value: "97%", note: "最近快照 05:30" },
  ],

  intakeSources: [
    {
      key: "mobile",
      icon: "smartphone",
      name: "手机",
      examples: "iPhone、安卓手机、微信/相册/文件App",
      access: "数据线、局域网投递、云端同步目录",
      target: "NAS 手机暂存区",
      status: "优先接入",
      risk: "中高",
      batchPrefix: "MOB",
      scanScope: "照片、视频、录音、聊天导出、文件 App 目录",
      securityDefault: "L3 敏感候选",
      precheck: "确认机主、时间段、隐私范围和是否允许导出",
      report: "设备清单、照片视频数量、文件大小、修改时间、重复候选",
      nasGate: "授权后进入 NAS 手机暂存区，按机主和日期保留原结构",
      aiGate: "L0-L2 可进 OCR/转写候选；照片人脸识别必须单独授权",
      next: "先采集照片、视频、录音、聊天导出和文件夹",
    },
    {
      key: "tablet",
      icon: "tablet",
      name: "iPad/平板",
      examples: "iPad、安卓平板、手写稿、会议资料",
      access: "数据线、AirDrop、同步目录",
      target: "NAS 平板暂存区",
      status: "优先接入",
      risk: "中",
      batchPrefix: "TAB",
      scanScope: "文档、图片、批注稿、会议资料、手写稿",
      securityDefault: "L2 内部候选",
      precheck: "确认设备主人、应用来源、会议资料范围",
      report: "文档类型、批注文件、图片数量、修改时间和重复候选",
      nasGate: "授权后进入 NAS 平板暂存区，保留应用导出结构",
      aiGate: "会议资料和手写稿先 OCR 候选，高密级不进训练",
      next: "重点采集文档、图片、批注稿和会议资料",
    },
    {
      key: "old-computer",
      icon: "monitor",
      name: "旧电脑/不同主机",
      examples: "旧 Mac、Windows、服务器、员工电脑",
      access: "局域网共享、远程索引、移动硬盘中转",
      target: "NAS 主机暂存区",
      status: "分批接入",
      risk: "中",
      batchPrefix: "PC",
      scanScope: "桌面、文档、项目盘、历史客户资料、软件工程目录",
      securityDefault: "L2 内部候选",
      precheck: "登记主机编号、使用人、系统类型、隐私排除目录",
      report: "主机文件总量、目录分布、格式分布、敏感候选和不可读目录",
      nasGate: "先只读扫描；授权后按主机编号进入 NAS 主机暂存区",
      aiGate: "项目文档可进候选；个人隐私、账号、密钥和高密级资料禁训",
      next: "先按电脑编号只读扫描，再汇总索引",
    },
    {
      key: "email",
      icon: "mail",
      name: "邮箱",
      examples: "企业邮箱、个人邮箱、历史客户邮件",
      access: "邮箱导出、EML/MSG、授权 API",
      target: "NAS 邮件暂存区",
      status: "待授权",
      risk: "高",
      batchPrefix: "MAIL",
      scanScope: "邮件包、EML/MSG、附件、客户往来记录",
      securityDefault: "L3 敏感候选",
      precheck: "确认邮箱账号、时间范围、客户范围和附件导出范围",
      report: "邮件数量、发件人、收件人、时间段、附件数量、敏感词命中",
      nasGate: "授权后邮件和附件分开入 NAS 邮件暂存区，保留原邮件来源",
      aiGate: "附件可 OCR 候选；客户隐私、合同、人事、财务邮件默认禁训",
      next: "先导出邮件清单和附件索引，敏感邮件不进训练",
    },
    {
      key: "cloud",
      icon: "cloud",
      name: "云端云盘/公有云",
      examples: "iCloud、OneDrive、百度网盘、阿里云盘、对象存储",
      access: "同步目录、云端清单、API",
      target: "NAS 云盘暂存区",
      status: "清单优先",
      risk: "中高",
      batchPrefix: "CLOUD",
      scanScope: "同步目录、云端清单、共享文件夹、对象存储清单",
      securityDefault: "L2 内部候选",
      precheck: "确认云盘账号、共享范围、同步方向和下载成本",
      report: "云端清单、本机同步差异、缺失文件、重复文件、版本冲突",
      nasGate: "先清单对账；授权后热数据进入 NAS 云盘暂存区",
      aiGate: "只允许 L0-L2 或已授权资料进入 AI 候选",
      next: "不全量下载，先清单对账和热数据同步",
    },
    {
      key: "nas",
      icon: "server",
      name: "NAS 总库",
      examples: "群晖、QNAP、TrueNAS、文件服务器",
      access: "SMB/AFP/NFS/API",
      target: "最终归总主库",
      status: "核心目标",
      risk: "中",
      batchPrefix: "NAS",
      scanScope: "暂存区、正式库、快照区、禁训区、部门共享区",
      securityDefault: "按目录继承密级",
      precheck: "确认共享协议、账号权限、快照策略和禁训区边界",
      report: "NAS 清单、卷容量、权限目录、快照状态、差异对账",
      nasGate: "NAS 本身是归总主库，先分暂存区和正式库",
      aiGate: "禁训区不进入 AI；L4-L6 仅本机/NAS 受控索引",
      next: "建立暂存区、正式库、快照区和禁训区",
    },
    {
      key: "usb",
      icon: "usb",
      name: "U盘/移动硬盘",
      examples: "客户拷贝盘、临时交接盘、移动 SSD",
      access: "本机挂载、只读扫描",
      target: "NAS 外接盘暂存区",
      status: "随到随扫",
      risk: "中高",
      batchPrefix: "USB",
      scanScope: "移动硬盘、U盘、客户交接盘、临时拷贝盘",
      securityDefault: "L2 内部候选",
      precheck: "确认来源人、用途、是否查毒、是否允许拷贝",
      report: "卷名、文件数量、格式分布、重复候选、风险文件和读取失败",
      nasGate: "先只读扫描；授权后进入 NAS 外接盘暂存区",
      aiGate: "只允许低密级成品进入候选；未知来源文件先隔离",
      next: "先查病毒和重复，再拷贝授权资料",
    },
    {
      key: "sd-card",
      icon: "sd-card",
      name: "SD卡/存储卡",
      examples: "相机卡、摄像机卡、录音笔卡",
      access: "读卡器、本机挂载",
      target: "NAS 素材暂存区",
      status: "优先保护",
      risk: "高",
      batchPrefix: "CARD",
      scanScope: "照片原片、视频原片、录音、卡内 DCIM 和设备目录",
      securityDefault: "L2 内部候选",
      precheck: "确认拍摄项目、拍摄日期、卡状态和是否先做镜像",
      report: "素材数量、拍摄时间、大小、卡结构、读取失败和重复候选",
      nasGate: "先镜像保护，再进入 NAS 素材暂存区",
      aiGate: "抽帧、转写、人脸识别候选必须在授权后执行",
      next: "先镜像备份，再抽帧、转写、人脸识别候选",
    },
    {
      key: "camera",
      icon: "camera",
      name: "相机/摄像机",
      examples: "单反、微单、运动相机、摄像机",
      access: "数据线、读卡器、采集站",
      target: "NAS 影像暂存区",
      status: "素材优先",
      risk: "中高",
      batchPrefix: "CAM",
      scanScope: "相机照片、视频、工程文件、代理文件、拍摄日期目录",
      securityDefault: "L2 内部候选",
      precheck: "确认设备、拍摄项目、素材范围和是否保留原文件名",
      report: "照片视频数量、格式、拍摄时间、设备目录和重复候选",
      nasGate: "授权后进入 NAS 影像暂存区，保留原始拍摄结构",
      aiGate: "抽帧和人脸识别必须走授权；原始素材不上传公有云",
      next: "采集照片、原片、成片、工程文件和拍摄日期",
    },
  ],

  intakeWorkflow: [
    { step: "01", title: "来源登记", detail: "记录来源、负责人、批次编号、默认密级和授权边界" },
    { step: "02", title: "扫描前确认", detail: "确认设备状态、样本目录、隐私排除、高密级候选和只读原则" },
    { step: "03", title: "只读采集", detail: "先做清单、路径、大小、修改时间，不移动、不删除、不改名" },
    { step: "04", title: "扫描报告", detail: "输出数量、体积、格式分布、敏感候选、重复候选和读取失败" },
    { step: "05", title: "NAS/AI 分流", detail: "授权资料进 NAS 暂存区；低密级资料再进入 OCR、转写、抽帧候选" },
  ],

  sampleValidationChecklist: [
    {
      step: "01",
      title: "接入前登记",
      owner: "项目负责人",
      gate: "确认来源人、设备类型、公司/部门/项目、默认密级和授权范围",
      output: "样本批次编号、来源说明、隐私排除目录、负责人",
    },
    {
      step: "02",
      title: "只读试扫",
      owner: "技术/档案管理员",
      gate: "只扫描 1 个小目录或 1 个设备样本，不移动、不删除、不改名",
      output: "文件数量、体积、格式分布、不可读条目、耗时记录",
    },
    {
      step: "03",
      title: "风险复核",
      owner: "部门负责人",
      gate: "检查 L4-L6、财务、人事、合同、隐私、密钥、未知来源文件",
      output: "禁训清单、隔离候选、高密级候选、人工复核意见",
    },
    {
      step: "04",
      title: "批次报告",
      owner: "档案管理员",
      gate: "确认批次摘要、批次历史、合并索引和浏览器脱敏索引一致",
      output: "批次报告、脱敏页面数据、合并索引摘要",
    },
    {
      step: "05",
      title: "NAS/AI 分流",
      owner: "最高授权人/系统管理员",
      gate: "授权后才进入 NAS 暂存区；L4-L6 不进公有云、不进 AI 训练",
      output: "NAS 暂存位置、AI 候选清单、禁训清单",
    },
    {
      step: "06",
      title: "扩大接入",
      owner: "项目主理人",
      gate: "样本验证通过后，按公司、部门、年份或设备分批扩大",
      output: "下一批扫描范围、预计体量、负责人、回滚方案",
    },
  ],

  sampleValidationFields: [
    { label: "样本来源类型", value: "硬盘 / NAS / 手机 / 云盘 / U盘 / SD卡 / 相机 / 邮箱" },
    { label: "来源名称", value: "设备编号、卷名、云盘账号或邮箱账号" },
    { label: "公司/部门/项目", value: "所属公司、部门、项目名称，允许临时项目公司" },
    { label: "负责人", value: "项目主理人、经办人、部门负责人、最高授权人" },
    { label: "样本范围", value: "先选 1 个小目录、1 个日期段或 1 个设备样本" },
    { label: "模糊时间段", value: "如 2018-2020、2024 年会、项目筹备期到收尾期" },
    { label: "隐私排除", value: "个人相册、账号密码、密钥、私人聊天、非授权客户资料" },
    { label: "默认密级", value: "默认 L2/L3；发现 L4-L6 立即标记禁训和人工复核" },
    { label: "扫描方式", value: "只读扫描；不移动、不删除、不改名真实文件" },
    { label: "NAS 暂存位置", value: "按来源类型、负责人、日期、批次编号进入暂存区" },
    { label: "AI 候选边界", value: "L0-L2 可候选；L3 授权后候选；L4-L6 禁止训练" },
    { label: "验收结果", value: "通过、待补充、隔离、暂停、扩大下一批" },
  ],

  fieldSearches: [
    { field: "companyType", label: "公司类型", placeholder: "如：项目公司、集团公司" },
    { field: "project", label: "项目名称", placeholder: "如：汽车品牌发布会" },
    { field: "projectType", label: "项目类型", placeholder: "如：投标、年会、述职" },
    { field: "company", label: "公司名称", placeholder: "如：广告公司" },
    { field: "departmentSystem", label: "部门建制", placeholder: "如：集团法务、营销中心" },
    { field: "department", label: "部门名称", placeholder: "如：策划部" },
    { field: "employee", label: "员工姓名", placeholder: "作者/负责人/参与人" },
    { field: "functionRole", label: "人事/职能", placeholder: "如：文案、顾问、剪辑" },
    { field: "periodSearchText", label: "周期阶段", placeholder: "如：2016到2019、Q1、筹备期" },
    { field: "assetStage", label: "完整状态", placeholder: "残缺、完整、待补充" },
    { field: "qualityLevel", label: "作品等级", placeholder: "优质、经典案例、示范文档" },
    { field: "level", label: "密级", placeholder: "L0、L3、L6" },
    { field: "storageSourceType", label: "存储来源", placeholder: "本机、云盘、NAS、U盘" },
    { field: "storageProvider", label: "存储名称", placeholder: "iCloud、NAS、移动硬盘" },
    { field: "accessMode", label: "接入方式", placeholder: "本机直连、同步目录、SMB" },
    { field: "syncStrategy", label: "同步策略", placeholder: "云本同步、只读索引、三方校验" },
    { field: "syncStatus", label: "同步状态", placeholder: "已同步、待校验、离线" },
    { field: "crossCheckPolicy", label: "交叉校验", placeholder: "清单、大小、哈希、差异报告" },
    { field: "storageRisk", label: "存储风险", placeholder: "低、中、中高、高" },
    { field: "storageCostLevel", label: "成本等级", placeholder: "低、中、中高、高" },
  ],

  workTypes: [
    { key: "all", icon: "layers", label: "全部类型", active: true },
    { key: "image", icon: "image", label: "图片/照片" },
    { key: "video", icon: "video", label: "视频/影视" },
    { key: "audio", icon: "audio-lines", label: "录音/音乐" },
    { key: "email", icon: "mail", label: "邮件" },
    { key: "contract", icon: "file-signature", label: "合同" },
    { key: "proposal", icon: "clipboard-list", label: "方案/提案" },
    { key: "bid", icon: "briefcase-business", label: "标书/投标文件" },
    { key: "ppt", icon: "presentation", label: "PPT" },
    { key: "word", icon: "file-text", label: "Word/文档" },
    { key: "excel", icon: "table-2", label: "Excel/电子表格" },
    { key: "scan", icon: "scan-text", label: "扫描件" },
    { key: "logo", icon: "badge-check", label: "标识/LOGO" },
    { key: "design", icon: "palette", label: "画册/设计稿" },
    { key: "code", icon: "code-2", label: "程序/代码" },
    { key: "database", icon: "database", label: "数据库/数据表" },
    { key: "archive", icon: "package", label: "压缩包/备份包" },
  ],

  quickFilters: [
    { key: "all", label: "全部", active: true },
    { key: "finish", label: "待收尾" },
    { key: "classic", label: "经典案例" },
    { key: "audio", label: "录音转写" },
    { key: "video", label: "视频" },
    { key: "private", label: "高密级" },
  ],

  tableColumns: [
    { key: "title", label: "标题" },
    { key: "project", label: "项目名称" },
    { key: "projectType", label: "项目类型" },
    { key: "company", label: "公司" },
    { key: "companyType", label: "公司类型" },
    { key: "department", label: "部门" },
    { key: "author", label: "员工/作者" },
    { key: "owner", label: "负责人" },
    { key: "ownerLevel", label: "负责人等级" },
    { key: "functionRole", label: "职能" },
    { key: "period", label: "周期" },
    { key: "periodSearchText", label: "周期阶段" },
    { key: "workType", label: "作品类型" },
    { key: "assetStage", label: "完整状态" },
    { key: "qualityLevel", label: "作品等级" },
    { key: "format", label: "格式" },
    { key: "storageSourceType", label: "存储来源" },
    { key: "storageProvider", label: "存储名称" },
    { key: "accessMode", label: "接入方式" },
    { key: "syncStrategy", label: "同步策略" },
    { key: "syncStatus", label: "同步状态" },
    { key: "storageRisk", label: "存储风险" },
    { key: "storageCostLevel", label: "成本等级" },
    { key: "status", label: "状态" },
    { key: "score", label: "评分" },
    { key: "level", label: "密级" },
  ],

  appearance: {
    palettes: [
      {
        key: "jade",
        label: "墨绿",
        accent: "#12756f",
        accentSoft: "#e3f3f0",
        sidebar: "#12201a",
        sidebarActive: "#1b3329",
        page: "#f5f6f2",
      },
      {
        key: "ink",
        label: "黑金",
        accent: "#9a6a18",
        accentSoft: "#f4ead4",
        sidebar: "#171513",
        sidebarActive: "#2b251c",
        page: "#f7f5ef",
      },
      {
        key: "blue",
        label: "深蓝",
        accent: "#315f8c",
        accentSoft: "#e2edf7",
        sidebar: "#111d2d",
        sidebarActive: "#1a314d",
        page: "#f4f7fa",
      },
      {
        key: "wine",
        label: "酒红",
        accent: "#9b3f52",
        accentSoft: "#f6e2e6",
        sidebar: "#211319",
        sidebarActive: "#3a202a",
        page: "#f8f3f4",
      },
    ],
    fonts: [
      {
        key: "system",
        label: "系统默认",
        value: 'Inter, "PingFang SC", "Microsoft YaHei", "Noto Sans CJK SC", Arial, sans-serif',
      },
      {
        key: "pingfang",
        label: "苹方",
        value: '"PingFang SC", "Noto Sans CJK SC", Arial, sans-serif',
      },
      {
        key: "yahei",
        label: "微软雅黑",
        value: '"Microsoft YaHei", "Noto Sans CJK SC", Arial, sans-serif',
      },
      {
        key: "songti",
        label: "宋体",
        value: '"Songti SC", "SimSun", serif',
      },
      {
        key: "kaiti",
        label: "楷体",
        value: '"Kaiti SC", "KaiTi", serif',
      },
    ],
    fontSize: {
      default: 15,
      min: 13,
      max: 18,
    },
  },
};
